version: '3.4'

services:
  db:
    image: mysql:5.7
    ports:
        - '3306:3306'
    environment:
        - MYSQL_DATABASE:'visseModas'
        - MYSQL_ROOT_PASSWORD:'root'
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  
  backendserver:
    build: .
    ports:
        - 8081
    links:
        - db
    depends_on:
        - db
    restart: always

  frontend:
    image: vissemodas-angular
    build: .
    links:
           - backendserver
    depends_on:
           - backendserver
    ports:
           - 80:80    